### ISSUE TITLE
vendor directory is missing

### ISSUE THREAD

**Issue by swizzly** [Icinga/icingaweb2-module-reactbundle#1]
Hi

The current version (3d43c8e) of reactbundle does not contain the vendor directory, hence Icingaweb2 can not work, it reports:

```
Warning: Uncaught exception 'ErrorException' with message 'require_once(/usr/share/icingaweb2/modules/reactbundle/vendor/autoload.php): failed to open stream: No such file or directory' in /usr/share/icingaweb2/modules/reactbundle/run.php:3 Stack trace: #0 /usr/share/icingaweb2/modules/reactbundle/run.php(3): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'require_once(/u...', '/usr/share/icin...', 3, Array) #1 /usr/share/icingaweb2/modules/reactbundle/run.php(3): require_once() #2 /usr/share/php/Icinga/Application/Modules/Module.php(1227): include('/usr/share/icin...') #3 /usr/share/php/Icinga/Application/Modules/Module.php(1214): Icinga\Application\Modules\Module->includeScript('/usr/share/icin...') #4 /usr/share/php/Icinga/Application/Modules/Module.php(424): Icinga\Application\Modules\Module->launchRunScript() #5 /usr/share/php/Icinga/Application/Modules/Manager.php(231): Icinga\Application\Modules\Module->register() #6 /usr/share/php/Icinga/Application/Modules/Manager.php(191): Icinga\Ap in /usr/share/icingaweb2/modules/reactbundle/run.php on line 3

Fatal error: main(): Failed opening required '/usr/share/icingaweb2/modules/reactbundle/vendor/autoload.php' (include_path='/usr/share/icingaweb2/library/vendor:.:/usr/share/pear:/usr/share/php') in /usr/share/icingaweb2/modules/reactbundle/run.php on line 3
```

I use icingaweb2: icingaweb2-2.5.1-1.el7.icinga.noarch

**Comment by swizzly** [comment]
Ok, I got it, you have to download a given release, e.g. the current release is 0.3.1, it has to be downloaded and not the master-branch...

**Comment by Thomas-Gelf** [comment]
Correct, that's also in the documentation. However, you're not the first one running into this issue - we should try to hack some kind of notification into the master, telling you that it won't work - instead of failing.
